[package]
name = "maya"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.23", features = ["derive"] }
inquire = "0.7.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
