name: Release `maya`

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: maya
            asset_name: maya-linux-amd64
          - os: macos-latest
            artifact_name: maya
            asset_name: maya-macos-amd64
          - os: windows-latest
            artifact_name: maya.exe
            asset_name: maya-windows-amd64.exe
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename artifact
        run: |
          mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
